name: figure-one-lab
channels:
  - conda-forge
  - bioconda
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scipy
  - anndata
  - scanpy
  - pybiomart
  - scvi-tools
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly  # remove this if you want GPU support
  - seaborn
  - jupyter
  - pip
  - pip:
    - scvi-tools