name: figure-one-lab
channels:
  - conda-forge
  - pytorch
  - defaults
  - bioconda
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - jupyter
  - anndata
  - scanpy
  - pybiomart
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - scvi-tools=0.17.4  # Pin scvi-tools version
  - pytorch-lightning=1.7.7  # Compatible version
  - torchmetrics=0.9.1  # Compatible version